### ISSUE TITLE
use case: self-updating

### ISSUE THREAD

**Issue by ssube** [ssube/isolex#313]
# Use Case

isolex should be self-updating, in cooperation with renovate and Gitlab.

When renovate submits an MR, Gitlab automatically builds it. When all checks have passed on the MR, it should be merged automatically. Other MRs should not be merged automatically.

- [ ] receive MR/PR status (#68 , #310)
  - [ ] filter by title: exclude `WIP:`
  - [ ] emit approval command (#555)
- [ ] receive MR/PR approval
  - [ ] filter by author: include @renovate-bot, @ssube
  - [ ] emit merge command (#555)
- [x] merge Github MR (#72)
- [ ] watch for new version (#559)
- [ ] deploy updated bot (#544)

When this is working reliably and documented, such that someone else can set it up, the bot shall be stable.
