### ISSUE TITLE
use case: deploy gate

### ISSUE THREAD

**Issue by ssube** [ssube/isolex#316]
# Use Case

After announcing build results (#315) and to act as a gate for automatic updates (#313), the bot should prompt users in Discord with a chance to cancel the deploy.

- [x] announce build results (#315)
- [ ] automatic merge (#313)
- [ ] prompt with cancel and confirm (#314)
- [ ] stop and restart bot (#544)
