### ISSUE TITLE
consistent data handling (dict/map)

### ISSUE THREAD

**Issue by ssube** [ssube/isolex#327]
### Summary

The bot stores data as a `Dict<string>` in some places and `Map<string, Array<string>>` in others. Converting between these two has led to some horrible hacks (https://github.com/ssube/isolex/commit/b9a9fa5aa7522f18a07c08486c4d7f3f4457c948) and inconsistent get-path behavior: some places use lodash `get`, some use jsonpath, and others use `Map.get` in a loop.

### Problems

- TypeORM does not serialize Maps correctly
- Handlebars does not get Map entries natively
- lodash `get` helper does not appear to get Map entries
- tons of hacky helpers to convert
- too many `mapToDict` calls will get _slow_ 

### TODO

- [x] jsonpath-plus update (#328)
- [x] find usage of `mapToDict` and `dictToMap` and `MapLike` helpers
- [x] look into immutable `Dict` data on entities (will help `Filter`s)
- [x] look into replacing lodash `get` with jsonpath
- [x] clean up conversion helpers

**Comment by ssube** [comment]
Replacing lodash's `get` with jsonpath-plus is a breaking change:

```
  113 passing (4s)
  9 pending
  3 failing

  1) match utility
       every operator
         should match a single string to itself:

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test/harness.ts:31:26)
      at /home/ssube/code/ssube/isolex/out/test.js:22:401
      at new Promise (<anonymous>)
      at Context.trackTest (out/test.js:22:328)
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:131:23)

  2) match utility
       any operator
         should match a single string to itself:

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test/harness.ts:31:26)
      at /home/ssube/code/ssube/isolex/out/test.js:22:401
      at new Promise (<anonymous>)
      at Context.trackTest (out/test.js:22:328)
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:131:23)

  3) match utility
       any operator
         should match a single string to many:

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test/harness.ts:31:26)
      at /home/ssube/code/ssube/isolex/out/test.js:22:401
      at new Promise (<anonymous>)
      at Context.trackTest (out/test.js:22:328)
      at processImmediate (internal/timers.js:439:21)
      at process.topLevelDomainCallback (domain.js:131:23)




=============================== Coverage summary ===============================
Statements   : 40.42% ( 1135/2808 )
Branches     : 30.76% ( 207/673 )
Functions    : 31.41% ( 218/694 )
Lines        : 39.41% ( 1062/2695 )
================================================================================
Makefile:110: recipe for target 'test-check' failed
make: *** [test-check] Error 3
```
