### ISSUE TITLE
add a user interface

### ISSUE THREAD

**Issue by ssube** [ssube/isolex#404]
### Summary

Now that the Express controller can serve plugin Endpoints, a pluggable UI is possible. Make it so.

### Scope

- [ ] top menu
  - [ ] login (paste token, set cookie)
  - [ ] server status (poll health endpoint #299 , red/green dot)
- [ ] left menu
  - [ ] list help (localized)
  - [ ] list metrics (auto-refresh w/ intervals)
  - [ ] create messages (send)
  - [ ] list recent messages (history)
  - [ ] admin stuff
    - [ ] reload (config, SIGHUP, #35 )
    - [ ] reset (counters, metrics, & services, SIGINT, #36 )
    - [ ] stop (SIGKILL, #22 )
    - [ ] view bot config (loaded version after parsing)
- misc
  - [ ] server loading spinner for admin reload/reset buttons

v2:

- top menu
  - update user settings
- left menu
  - list commands (by noun, verb)
  - admin stuff
    - update log level by service (#292 )
    - list logs
    - list services

### Questions

- should probably be an out-of-tree plugin
- should match the project structure (rollup, config, etc)
- should be compatible with recent Chrome
- should use React, MobX
- might need a CSS library

**Comment by ssube** [comment]
For the server status indicator, the Sidekiq job dashboard has the right look: 
![image](https://user-images.githubusercontent.com/451959/64490296-1fc0e600-d221-11e9-9fdf-09f1c7473b91.png)

For the metrics interval, the Grafana time range is the right control (with slightly more reasonable values): 
![image](https://user-images.githubusercontent.com/451959/64490320-51d24800-d221-11e9-872c-4e96b59c37f5.png)
